### ISSUE TITLE
Invalid Mesh

### ISSUE THREAD

**Issue by SpeedyMouse76** [structureio/sample-scanner#13]
Hello,

I run this example app without a license key. After every scan I get the error message "Invalid Mesh". What I do wrong or do I need a license key ?

**Comment by StructureShield** [comment]
You'll need a license key to get a valid and complete mesh. Please see the README.md file in the code directory and the "Documentation" folder in the Structure SDK download for guidance.

**Comment by SpeedyMouse76** [comment]
The link from the documentation to get the license key doesn't work. What is the correct link ? Is the license key include if I had by a sensor or is that a extra payment?

**Comment by StructureShield** [comment]
-- Please reply above this line --


Hello Structureio/sample-Scanner,

We received your email request!

Someone from our team will get back to you as soon as possible.

Happy Scanning,
The Structure Team Bot

_STRUCTURE 2023 HOLIDAY CALENDAR (We will be closed on these dates.)_

	* Veterans Day(Fri, Nov 10)
	* Thanksgiving _(Thu, Nov 23)_
	* Thanksgiving _(Fri, Nov 24)_
	* Christmas Eve _(Fri, Dec 22)_
	* Christmas Day _(Mon, Dec 25)_
	* New Years Eve _(Fri, Dec 29)_

**Comment by StructureShield** [comment]
You should be able to create an account here: https://console.cloud.structure.io/login

After setting up your account, a team member will contact you to assist in getting up and running. The standard license includes the Structure Sensor scan export feature. In order to export the mesh, all apps require a license key.

Additional paid features, such as Apple TrueDepth and Apple LiDAR support, are available. If you are interested in testing those out just let us know. We do offer educational and small business terms.
